### ISSUE TITLE
AWS Kubernetes -> Authentication Error

### ISSUE THREAD

**Issue by thomasyu888** [elixir-europe/WES-ELIXIR#155]
## Describe the bug
After setting up a an AWS EKS cluster, I followed the deployment instructions and 
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cwltool/main.py", line 816, in main
    logger=_logger)
  File "/app/src/cwl-tes/cwl_tes/main.py", line 224, in tes_execute
    return job_executor(process, job_order, runtime_context, logger)
  File "/usr/local/lib/python3.6/site-packages/cwltool/executors.py", line 39, in __call__
    return self.execute(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cwltool/executors.py", line 101, in execute
    self.run_jobs(process, job_order_object, logger, runtime_context)
  File "/usr/local/lib/python3.6/site-packages/cwltool/executors.py", line 328, in run_jobs
    self.wait_for_next_completion(runtime_context)
  File "/usr/local/lib/python3.6/site-packages/cwltool/executors.py", line 294, in wait_for_next_completion
    raise self.exceptions[0]
  File "/usr/local/lib/python3.6/site-packages/cwltool/executors.py", line 264, in runner
    job.run(runtime_context)
  File "/app/src/cwl-tes/cwl_tes/tes.py", line 396, in run
    raise WorkflowException(e)
cwltool.errors.WorkflowException:
<status code> 401
<response> {
  "timestamp" : "2020-04-30T06:19:47.028+0000",
  "status" : 401,
  "error" : "unauthorized",
  "message" : "Full authentication is required to access this resource",
  "path" : "/v1/tasks",
  "error_description" : "Full authentication is required to access this resource"
}

```

## To Reproduce
After following the deployment readme and the repository readme, I start a workflow and I see that this command is run:

```
"command": "cwl-tes --debug --leave-outputs --remote-storage-url ftp://ftp-private.ebi.ac.uk/upload/foivos --tes https://csc-tesk.c03.k8s-popup.csc.fi/ /data/output/65VKC6/workflow_files/repo/testdata/echo.cwl /data/output/65VKC6/workflow_files/echo.yml",
```

I see this in the code in the `run_workflows.py` and I can most certainly comment out the `--remote-storage-url`, but how do I specify `--tes ...`   Is this supposed to be some other service I set up?

```
kubectl get svc
cwlwes           ClusterIP   ...   <none>        8080/TCP    21h
cwlwes-certbot   ClusterIP   ...   <none>        8080/TCP    21h
flower           ClusterIP   ....   <none>        5555/TCP    21h
kubernetes       ClusterIP   ...     <none>        443/TCP     23h
mongodb          ClusterIP   ...   <none>        27017/TCP   21h
rabbitmq         ClusterIP   ...   <none>        5672/TCP    21h
```

```
docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                                    NAMES
aa246d492843        mher/flower:0.9              "flower flower --bro…"   18 minutes ago      Up 18 minutes       0.0.0.0:5555->5555/tcp                                                   app_flower_1
a7ddf52ae5e5        elixircloud/cwl-wes:latest   "bash -c 'cd /app/cw…"   18 minutes ago      Up 18 minutes                                                                                app_wes-worker_1
b7ab96a60e5a        elixircloud/cwl-wes:latest   "bash -c 'cd /app/cw…"   18 minutes ago      Up 18 minutes       0.0.0.0:7777->8080/tcp                                                   app_wes_1
8a7c7fe80801        rabbitmq:3-management        "docker-entrypoint.s…"   18 minutes ago      Up 18 minutes       4369/tcp, 5671/tcp, 15671-15672/tcp, 25672/tcp, 0.0.0.0:5672->5672/tcp   app_rabbitmq_1
235ab2cd9c0b        mongo:3.2                    "docker-entrypoint.s…"   18 minutes ago      Up 18 minutes       0.0.0.0:27017->27017/tcp  
```

## Expected behavior
Resolve the permission issue and run example workflow.  Does the deployment include `TES`?

## Software
 - AMAZON EKS

**Comment by thomasyu888** [comment]
More notes:  I switched the code in `run_workflow.py` to

```
    # Build command
    # command_list = [
    #     'cwl-tes',
    #     '--debug',
    #     '--leave-outputs',
    #     # '--remote-storage-url', remote_storage_url,
    #     '--tes', tes_url,
    #     cwl_path,
    #     param_file_path
    # ]
    command_list = [
        'cwltool',
        '--debug',
        #'--leave-outputs',
        # '--remote-storage-url', remote_storage_url,
        #'--tes', tes_url,
        cwl_path,
        param_file_path
    ]
```

I did get the workflow to start running but it appears to be stuck in a "RUNNING" state?

```
{
  "run_id": "3O2CYU",
  "state": "RUNNING"
}
```

Does this mean I set up the kubernetes deployment incorrectly?

**Comment by uniqueg** [comment]
Hi Thomas! Thanks for your interest in the service. I have to warn you that the service is still very much in alpha, and also the state of the docs could surely be better - apologies for that!

The good thing is that you managed to put your finger on pretty much all critical/important points. So let me try to get to them one by one:

* **TES** is indeed another service that is _not_ automatically co-deployed together with cwl-WES. The decoupling of workflow execution (or better call it interpretation/scheduling) service and task execution service is intentional - it allows for more flexibility in realizing different use cases (see [this doc] for more info). The used TES service should follow the [GA4GH TES specs](https://github.com/ga4gh/task-execution-schemas/blob/master/openapi/task_execution.swagger.yaml). TESK, our own TES implementation, is available [here](https://github.com/EMBL-EBI-TSI/TESK). We _usually_ (but of course not right now :roll_eyes: because we are heavily working on them) have a TESK instance available that can be used for testing. You can check the state of our deployments [here](https://github.com/elixir-cloud-aai/elixir-cloud-aai/blob/dev/resources/resources.md). It is one of these instances that is set in the [cwl-WES config](cwl_wes/config/app_config.yaml) as the default TES: `https://csc-tesk.c03.k8s-popup.csc.fi/` (you can visit it and explore the API via Swagger). The reason why you are getting the `401` error is that currently, for testing purposes on that TESK instance, we require an access token with specific claims to be provided with each call. If you are interested in deploying TESK yourself, we are currently in the process of writing and testing Helm charts for TESK deployment on k8s and OpenShift, so that should probably make it easier to deploy an instance.

* Regarding **storage**, for the moment TESK can only handle FTP and HTTP URLs. As we are mostly testing the app with an FTP server, we currently expect default host, login and password values in a `.netrc` file. We are aware that this is a serious limitation and we have plans to provide S3 support over the next couple of months, as well as get rid of non-essential dependencies in that respect. Disabling `--remote-storage-url` will very likely mean that you are restricted to workflows with no input and output, so that's not really useful. If you do not have access to an FTP server, you can contact me via email (in my profile), and I can provide you with credentials for our server for testing purposes. Even better, you can reach out to us via Slack (link available here: https://github.com/elixir-cloud-aai/elixir-cloud-aai), as we could more easily help you debug if you are interested to continue with the installation of cwl-TES and TESK.

* Your workaround with `cwltool` rather than `cwl-tes` should indeed start a workflow. The problem here is that since the WES and TES specs currently do not provide a callback mechanism for updating task state, we are parsing the `cwl-tes` log manually and sending state change and other signals to our task monitor daemon (`cwl-tes` polls task state from TES every 2 sec or so!). The behavior for this is of course not documented/predictable if the log format changes (which sometimes happens if we upgrade `cwl-tes`), which, I suspect, will be quite different for `cwltool`.  It's really not a nice setup, and we have plans to overhaul this mechanism. But as it works more or less for our purposes, it's not at the top of our list. Out of curiosity: does your workflow finish with this setup? You can probably tell from the Celery logs. In any case, I am really grateful for this test, as I should probably add some mechanism that checks whether we are dealing with the correct log format and set the run state to `UNKNOWN` at some point. Really not good to have zombie runs...

Again, we're very happy to help you with the deployment and testing if you'd like, so consider joining our Slack - you are very welcome!

**Comment by thomasyu888** [comment]
Thanks @uniqueg for the thoughtful response!  I will work through this and report back.  I am definitely interested in getting this up and running and can also assist with the documentation as I go along.

* TES:  Perfect.   We have experimented with toil to manage workflow scaling, but  I would be interested in standing this up. 

* I joined the slack - Would love to be able to test out `cwl-TES` and `TESK`

* Here are the celery logs:

```
[2020-04-30 20:05:43,715: INFO/ForkPoolWorker-2] /usr/local/bin/cwltool 1.0.20181217162649
[2020-04-30 20:05:43,718: INFO/ForkPoolWorker-2] Resolved "/data/output/HI5KJZ/workflow_files/repo/testdata/echo.cwl" to "file:///data/output/HI5KJZ/workflow_files/repo/testdata/echo.cwl"
[2020-04-30 20:05:45,403: INFO/ForkPoolWorker-2] [job echo.cwl] initializing from file:///data/output/HI5KJZ/workflow_files/repo/testdata/echo.cwl
[2020-04-30 20:05:45,403: INFO/ForkPoolWorker-2] [job echo.cwl] {
[2020-04-30 20:05:45,403: INFO/ForkPoolWorker-2]     "message": "hellow"
[2020-04-30 20:05:45,403: INFO/ForkPoolWorker-2] }
[2020-04-30 20:05:45,404: INFO/ForkPoolWorker-2] [job echo.cwl] path mappings is {}
[2020-04-30 20:05:45,404: INFO/ForkPoolWorker-2] [job echo.cwl] command line bindings is [
[2020-04-30 20:05:45,405: INFO/ForkPoolWorker-2]     {
[2020-04-30 20:05:45,405: INFO/ForkPoolWorker-2]         "position": [
[2020-04-30 20:05:45,405: INFO/ForkPoolWorker-2]             -1000000,
[2020-04-30 20:05:45,405: INFO/ForkPoolWorker-2]             0
[2020-04-30 20:05:45,405: INFO/ForkPoolWorker-2]         ],
[2020-04-30 20:05:45,406: INFO/ForkPoolWorker-2]         "datum": "echo"
[2020-04-30 20:05:45,406: INFO/ForkPoolWorker-2]     },
[2020-04-30 20:05:45,406: INFO/ForkPoolWorker-2]     {
[2020-04-30 20:05:45,406: INFO/ForkPoolWorker-2]         "position": [
[2020-04-30 20:05:45,406: INFO/ForkPoolWorker-2]             1,
[2020-04-30 20:05:45,406: INFO/ForkPoolWorker-2]             "message"
[2020-04-30 20:05:45,407: INFO/ForkPoolWorker-2]         ],
[2020-04-30 20:05:45,407: INFO/ForkPoolWorker-2]         "datum": "hellow"
[2020-04-30 20:05:45,407: INFO/ForkPoolWorker-2]     }
[2020-04-30 20:05:45,407: INFO/ForkPoolWorker-2] ]
[2020-04-30 20:05:45,408: INFO/ForkPoolWorker-2] [job echo.cwl] initial work dir {}
[2020-04-30 20:05:45,408: INFO/ForkPoolWorker-2] [job echo.cwl] /tmp/dw2hrqmt$ echo \
[2020-04-30 20:05:45,408: INFO/ForkPoolWorker-2]     hellow
[2020-04-30 20:05:45,414: INFO/ForkPoolWorker-2] hellow
[2020-04-30 20:05:45,416: INFO/ForkPoolWorker-2] Could not collect memory usage, job ended before monitoring began.
[2020-04-30 20:05:45,417: INFO/ForkPoolWorker-2] [job echo.cwl] completed success
[2020-04-30 20:05:45,417: INFO/ForkPoolWorker-2] [job echo.cwl] {}
[2020-04-30 20:05:45,418: INFO/ForkPoolWorker-2] [job echo.cwl] Removing input staging directory /tmp/tmpn3qyr7nd
[2020-04-30 20:05:45,418: INFO/ForkPoolWorker-2] [job echo.cwl] Removing temporary directory /tmp/tmppa18cotr
[2020-04-30 20:05:45,419: INFO/ForkPoolWorker-2] {}
[2020-04-30 20:05:45,419: INFO/ForkPoolWorker-2] Final process status is success
[2020-04-30 20:05:45,496: INFO/ForkPoolWorker-2] Task tasks.run_workflow[ed1313e7-2bf3-444a-b20f-34bc7201d6de] succeeded in 2.513748099998338s: (0, ['/usr/local/bin/cwltool 1.0.20181217162649', 'Resolved "/data/output/HI5KJZ/workflow_files/repo/testdata/echo.cwl" to "file:///data/output/HI5KJZ/workflow_files/repo/testdata/echo.cwl"', '[job echo.cwl] initializing from file:///data/output/HI5KJZ/workflow_files/repo/testdata/echo.cwl', '[job echo.cwl] {', '    "message": "hellow"', '}', '[job echo.cwl] path mappings is {}', '[job echo.cwl] command line bindings is [', '    {', '        "position": [', '            -1000000,', '            0', '        ],', '        "datum": "echo"', '    },', '    {', '        "position": [', '            1,', '            "message"', '        ],', '        "datum": "hellow"', '    }', ']', '[job echo.cwl] initial work dir {}', '[job echo.cwl] /tmp/dw2hrqmt$ echo \', '    hellow', 'hellow', 'Could not collect memory usage, job ended before monitoring began.', '[job echo.cwl] completed success', '[job echo.cwl] {}', '[job echo.cwl] Removing input staging directory /tmp/tmpn3qyr7nd', '[job echo.cwl] Removing temporary directory /tmp/tmppa18cotr', '{}', 'Final process status is success'], [])
```

Looking forward to getting this up and running!  Also, I'm very new to Kubernetes (I did watch a couple of videos).  I am unsure how to check if I am actually utilizing the cluster when doing `docker-compose up -d`

**Comment by uniqueg** [comment]
@thomasyu888 Fantastic - very happy to hear that! I'm out for the weekend, will get back to this Monday

**Comment by uniqueg** [comment]
I'll close this as I think all the pain points brought up here are already described in other issues. Apart from that the bottom line is that this and the related services need far better documentation.
